package pe.com.cotic.test.modelo;

// Generated 14/11/2017 04:57:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Acceso generated by hbm2java
 */
public class Acceso implements java.io.Serializable {

	private Integer codigoAcceso;
	private Integer codigoUsuario;
	private Date fechaAcceso;
	private Date horaAcceso;
	private Boolean accionAcceso;

	public Acceso() {
	}

	public Acceso(Integer codigoUsuario, Date fechaAcceso, Date horaAcceso,
			Boolean accionAcceso) {
		this.codigoUsuario = codigoUsuario;
		this.fechaAcceso = fechaAcceso;
		this.horaAcceso = horaAcceso;
		this.accionAcceso = accionAcceso;
	}

	public Integer getCodigoAcceso() {
		return this.codigoAcceso;
	}

	public void setCodigoAcceso(Integer codigoAcceso) {
		this.codigoAcceso = codigoAcceso;
	}

	public Integer getCodigoUsuario() {
		return this.codigoUsuario;
	}

	public void setCodigoUsuario(Integer codigoUsuario) {
		this.codigoUsuario = codigoUsuario;
	}

	public Date getFechaAcceso() {
		return this.fechaAcceso;
	}

	public void setFechaAcceso(Date fechaAcceso) {
		this.fechaAcceso = fechaAcceso;
	}

	public Date getHoraAcceso() {
		return this.horaAcceso;
	}

	public void setHoraAcceso(Date horaAcceso) {
		this.horaAcceso = horaAcceso;
	}

	public Boolean getAccionAcceso() {
		return this.accionAcceso;
	}

	public void setAccionAcceso(Boolean accionAcceso) {
		this.accionAcceso = accionAcceso;
	}

}
