package pe.com.cotic.test.modelo;

// Generated 07/09/2017 11:40:56 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by hbm2java
 */
public class Curso implements java.io.Serializable {

	private Integer codigoCurso;
	private String tituloCurso;
	private String descripcionCurso;
	private byte[] imagenCurso;
	private String fechaInicioCurso;
	private String fechaFinCurso;
	private int flagMostrarRespuestaCorrectaCurso;
	private String tiempoCurso;
	private int estado;
	private Set preguntas = new HashSet(0);
	private Set usuariocursos = new HashSet(0);

	public Curso() {
	}

	public Curso(String tituloCurso, String descripcionCurso,
			String fechaInicioCurso, int flagMostrarRespuestaCorrectaCurso,
			int estado) {
		this.tituloCurso = tituloCurso;
		this.descripcionCurso = descripcionCurso;
		this.fechaInicioCurso = fechaInicioCurso;
		this.flagMostrarRespuestaCorrectaCurso = flagMostrarRespuestaCorrectaCurso;
		this.estado = estado;
	}

	public Curso(String tituloCurso, String descripcionCurso,
			byte[] imagenCurso, String fechaInicioCurso, String fechaFinCurso,
			int flagMostrarRespuestaCorrectaCurso, String tiempoCurso,
			int estado, Set preguntas, Set usuariocursos) {
		this.tituloCurso = tituloCurso;
		this.descripcionCurso = descripcionCurso;
		this.imagenCurso = imagenCurso;
		this.fechaInicioCurso = fechaInicioCurso;
		this.fechaFinCurso = fechaFinCurso;
		this.flagMostrarRespuestaCorrectaCurso = flagMostrarRespuestaCorrectaCurso;
		this.tiempoCurso = tiempoCurso;
		this.estado = estado;
		this.preguntas = preguntas;
		this.usuariocursos = usuariocursos;
	}

	public Integer getCodigoCurso() {
		return this.codigoCurso;
	}

	public void setCodigoCurso(Integer codigoCurso) {
		this.codigoCurso = codigoCurso;
	}

	public String getTituloCurso() {
		return this.tituloCurso;
	}

	public void setTituloCurso(String tituloCurso) {
		this.tituloCurso = tituloCurso;
	}

	public String getDescripcionCurso() {
		return this.descripcionCurso;
	}

	public void setDescripcionCurso(String descripcionCurso) {
		this.descripcionCurso = descripcionCurso;
	}

	public byte[] getImagenCurso() {
		return this.imagenCurso;
	}

	public void setImagenCurso(byte[] imagenCurso) {
		this.imagenCurso = imagenCurso;
	}

	public String getFechaInicioCurso() {
		return this.fechaInicioCurso;
	}

	public void setFechaInicioCurso(String fechaInicioCurso) {
		this.fechaInicioCurso = fechaInicioCurso;
	}

	public String getFechaFinCurso() {
		return this.fechaFinCurso;
	}

	public void setFechaFinCurso(String fechaFinCurso) {
		this.fechaFinCurso = fechaFinCurso;
	}

	public int getFlagMostrarRespuestaCorrectaCurso() {
		return this.flagMostrarRespuestaCorrectaCurso;
	}

	public void setFlagMostrarRespuestaCorrectaCurso(
			int flagMostrarRespuestaCorrectaCurso) {
		this.flagMostrarRespuestaCorrectaCurso = flagMostrarRespuestaCorrectaCurso;
	}

	public String getTiempoCurso() {
		return this.tiempoCurso;
	}

	public void setTiempoCurso(String tiempoCurso) {
		this.tiempoCurso = tiempoCurso;
	}

	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	public Set getPreguntas() {
		return this.preguntas;
	}

	public void setPreguntas(Set preguntas) {
		this.preguntas = preguntas;
	}

	public Set getUsuariocursos() {
		return this.usuariocursos;
	}

	public void setUsuariocursos(Set usuariocursos) {
		this.usuariocursos = usuariocursos;
	}

}
