package pe.com.cotic.test.modelo;

// Generated 12/01/2018 05:18:12 PM by Hibernate Tools 3.4.0.CR1

/**
 * Parametro generated by hbm2java
 */
public class Parametro implements java.io.Serializable {

	private Integer codigoParametro;
	private String descripcionParametro;
	private String valorParametro;
	private String estadoParametro;
	private Integer codigoInstitucion;

	public Parametro() {
	}

	public Parametro(String descripcionParametro, String valorParametro,
			String estadoParametro, Integer codigoInstitucion) {
		this.descripcionParametro = descripcionParametro;
		this.valorParametro = valorParametro;
		this.estadoParametro = estadoParametro;
		this.codigoInstitucion = codigoInstitucion;
	}

	public Integer getCodigoParametro() {
		return this.codigoParametro;
	}

	public void setCodigoParametro(Integer codigoParametro) {
		this.codigoParametro = codigoParametro;
	}

	public String getDescripcionParametro() {
		return this.descripcionParametro;
	}

	public void setDescripcionParametro(String descripcionParametro) {
		this.descripcionParametro = descripcionParametro;
	}

	public String getValorParametro() {
		return this.valorParametro;
	}

	public void setValorParametro(String valorParametro) {
		this.valorParametro = valorParametro;
	}

	public String getEstadoParametro() {
		return this.estadoParametro;
	}

	public void setEstadoParametro(String estadoParametro) {
		this.estadoParametro = estadoParametro;
	}

	public Integer getCodigoInstitucion() {
		return this.codigoInstitucion;
	}

	public void setCodigoInstitucion(Integer codigoInstitucion) {
		this.codigoInstitucion = codigoInstitucion;
	}

}
