package pe.com.cotic.test.modelo;

// Generated 12/09/2017 12:25:55 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Pregunta generated by hbm2java
 */
public class Pregunta implements java.io.Serializable {

	private Integer codigoPregunta;
	private Portafolio portafolio;
	private String tituloPregunta;
	private int estado;
	private byte[] imagenPregunta;
	private Set alternativas = new HashSet(0);

	public Pregunta() {
	}

	public Pregunta(Portafolio portafolio, String tituloPregunta, int estado) {
		this.portafolio = portafolio;
		this.tituloPregunta = tituloPregunta;
		this.estado = estado;
	}

	public Pregunta(Portafolio portafolio, String tituloPregunta, int estado,
			byte[] imagenPregunta, Set alternativas) {
		this.portafolio = portafolio;
		this.tituloPregunta = tituloPregunta;
		this.estado = estado;
		this.imagenPregunta = imagenPregunta;
		this.alternativas = alternativas;
	}

	public Integer getCodigoPregunta() {
		return this.codigoPregunta;
	}

	public void setCodigoPregunta(Integer codigoPregunta) {
		this.codigoPregunta = codigoPregunta;
	}

	public Portafolio getPortafolio() {
		return this.portafolio;
	}

	public void setPortafolio(Portafolio portafolio) {
		this.portafolio = portafolio;
	}

	public String getTituloPregunta() {
		return this.tituloPregunta;
	}

	public void setTituloPregunta(String tituloPregunta) {
		this.tituloPregunta = tituloPregunta;
	}

	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	public byte[] getImagenPregunta() {
		return this.imagenPregunta;
	}

	public void setImagenPregunta(byte[] imagenPregunta) {
		this.imagenPregunta = imagenPregunta;
	}

	public Set getAlternativas() {
		return this.alternativas;
	}

	public void setAlternativas(Set alternativas) {
		this.alternativas = alternativas;
	}

}
