package pe.com.cotic.test.modelo;

// Generated 07/09/2017 11:40:56 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Pregunta generated by hbm2java
 */
public class Pregunta implements java.io.Serializable {

	private Integer codigoPregunta;
	private Curso curso;
	private String tituloPregunta;
	private int estado;
	private Set alternativas = new HashSet(0);

	public Pregunta() {
	}

	public Pregunta(Curso curso, String tituloPregunta, int estado) {
		this.curso = curso;
		this.tituloPregunta = tituloPregunta;
		this.estado = estado;
	}

	public Pregunta(Curso curso, String tituloPregunta, int estado,
			Set alternativas) {
		this.curso = curso;
		this.tituloPregunta = tituloPregunta;
		this.estado = estado;
		this.alternativas = alternativas;
	}

	public Integer getCodigoPregunta() {
		return this.codigoPregunta;
	}

	public void setCodigoPregunta(Integer codigoPregunta) {
		this.codigoPregunta = codigoPregunta;
	}

	public Curso getCurso() {
		return this.curso;
	}

	public void setCurso(Curso curso) {
		this.curso = curso;
	}

	public String getTituloPregunta() {
		return this.tituloPregunta;
	}

	public void setTituloPregunta(String tituloPregunta) {
		this.tituloPregunta = tituloPregunta;
	}

	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	public Set getAlternativas() {
		return this.alternativas;
	}

	public void setAlternativas(Set alternativas) {
		this.alternativas = alternativas;
	}

}
