package pe.com.cotic.test.modelo;

// Generated 28/09/2017 10:33:35 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Respuestacabecera generated by hbm2java
 */
public class Respuestacabecera implements java.io.Serializable {

	private Integer codigoRespuestaCabecera;
	private Usuario usuario;
	private Portafolio portafolio;
	private String fechaRespuesta;
	private Date fechaSincronizacion;
	private Set respuestadetalles = new HashSet(0);

	public Respuestacabecera() {
	}

	public Respuestacabecera(Usuario usuario, Portafolio portafolio,
			String fechaRespuesta, Date fechaSincronizacion) {
		this.usuario = usuario;
		this.portafolio = portafolio;
		this.fechaRespuesta = fechaRespuesta;
		this.fechaSincronizacion = fechaSincronizacion;
	}

	public Respuestacabecera(Usuario usuario, Portafolio portafolio,
			String fechaRespuesta, Date fechaSincronizacion,
			Set respuestadetalles) {
		this.usuario = usuario;
		this.portafolio = portafolio;
		this.fechaRespuesta = fechaRespuesta;
		this.fechaSincronizacion = fechaSincronizacion;
		this.respuestadetalles = respuestadetalles;
	}

	public Integer getCodigoRespuestaCabecera() {
		return this.codigoRespuestaCabecera;
	}

	public void setCodigoRespuestaCabecera(Integer codigoRespuestaCabecera) {
		this.codigoRespuestaCabecera = codigoRespuestaCabecera;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Portafolio getPortafolio() {
		return this.portafolio;
	}

	public void setPortafolio(Portafolio portafolio) {
		this.portafolio = portafolio;
	}

	public String getFechaRespuesta() {
		return this.fechaRespuesta;
	}

	public void setFechaRespuesta(String fechaRespuesta) {
		this.fechaRespuesta = fechaRespuesta;
	}

	public Date getFechaSincronizacion() {
		return this.fechaSincronizacion;
	}

	public void setFechaSincronizacion(Date fechaSincronizacion) {
		this.fechaSincronizacion = fechaSincronizacion;
	}

	public Set getRespuestadetalles() {
		return this.respuestadetalles;
	}

	public void setRespuestadetalles(Set respuestadetalles) {
		this.respuestadetalles = respuestadetalles;
	}

}
