package pe.com.cotic.test.modelo;

// Generated 12/09/2017 12:25:55 PM by Hibernate Tools 4.0.0

/**
 * Rolmenu generated by hbm2java
 */
public class Rolmenu implements java.io.Serializable {

	private Integer codigoRolMenu;
	private Rol rol;
	private Menu menu;

	public Rolmenu() {
	}

	public Rolmenu(Rol rol, Menu menu) {
		this.rol = rol;
		this.menu = menu;
	}

	public Integer getCodigoRolMenu() {
		return this.codigoRolMenu;
	}

	public void setCodigoRolMenu(Integer codigoRolMenu) {
		this.codigoRolMenu = codigoRolMenu;
	}

	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	public Menu getMenu() {
		return this.menu;
	}

	public void setMenu(Menu menu) {
		this.menu = menu;
	}

}
