package pe.com.cotic.test.modelo;

// Generated 07/09/2017 11:40:56 PM by Hibernate Tools 4.0.0

/**
 * Usuariocurso generated by hbm2java
 */
public class Usuariocurso implements java.io.Serializable {

	private Integer codigoUsuarioCurso;
	private Usuario usuario;
	private Curso curso;

	public Usuariocurso() {
	}

	public Usuariocurso(Usuario usuario, Curso curso) {
		this.usuario = usuario;
		this.curso = curso;
	}

	public Integer getCodigoUsuarioCurso() {
		return this.codigoUsuarioCurso;
	}

	public void setCodigoUsuarioCurso(Integer codigoUsuarioCurso) {
		this.codigoUsuarioCurso = codigoUsuarioCurso;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Curso getCurso() {
		return this.curso;
	}

	public void setCurso(Curso curso) {
		this.curso = curso;
	}

}
