package pe.com.cotic.test.modelo;

// Generated 28/09/2017 10:33:35 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private Integer codigoUsuario;
	private Institucion institucion;
	private String usuario;
	private String clave;
	private String dni;
	private String apellidoPaterno;
	private String apellidoMaterno;
	private String nombres;
	private Date fechaNacimiento;
	private String correo;
	private String telefono;
	private String celular;
	private int estado;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private String sexo;
	private Set rolusuarios = new HashSet(0);
	private Set usuariodispositivos = new HashSet(0);
	private Set usuarioportafolios = new HashSet(0);
	private Set respuestacabeceras = new HashSet(0);

	public Usuario() {
		institucion = new Institucion(); 
	}

	public Usuario(Institucion institucion, String clave, String dni,
			String apellidoPaterno, String nombres, Date fechaNacimiento,
			int estado, String usuarioCreacion, Date fechaCreacion) {
		this.institucion = institucion;
		this.clave = clave;
		this.dni = dni;
		this.apellidoPaterno = apellidoPaterno;
		this.nombres = nombres;
		this.fechaNacimiento = fechaNacimiento;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
	}

	public Usuario(Institucion institucion, String usuario, String clave,
			String dni, String apellidoPaterno, String apellidoMaterno,
			String nombres, Date fechaNacimiento, String correo,
			String telefono, String celular, int estado,
			String usuarioCreacion, Date fechaCreacion,
			String usuarioModificacion, Date fechaModificacion, String sexo,
			Set rolusuarios, Set usuariodispositivos, Set usuarioportafolios,
			Set respuestacabeceras) {
		this.institucion = institucion;
		this.usuario = usuario;
		this.clave = clave;
		this.dni = dni;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.nombres = nombres;
		this.fechaNacimiento = fechaNacimiento;
		this.correo = correo;
		this.telefono = telefono;
		this.celular = celular;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.sexo = sexo;
		this.rolusuarios = rolusuarios;
		this.usuariodispositivos = usuariodispositivos;
		this.usuarioportafolios = usuarioportafolios;
		this.respuestacabeceras = respuestacabeceras;
	}

	public Integer getCodigoUsuario() {
		return codigoUsuario;
	}

	public void setCodigoUsuario(Integer codigoUsuario) {
		this.codigoUsuario = codigoUsuario;
	}

	public Institucion getInstitucion() {
		return institucion;
	}

	public void setInstitucion(Institucion institucion) {
		this.institucion = institucion;
	}

	public String getUsuario() {
		return usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getClave() {
		return clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	public String getDni() {
		return dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getApellidoPaterno() {
		return apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	public String getApellidoMaterno() {
		return apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	public String getNombres() {
		return nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public Date getFechaNacimiento() {
		return fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public String getCorreo() {
		return correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getTelefono() {
		return telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getCelular() {
		return celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	public int getEstado() {
		return estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	public String getUsuarioCreacion() {
		return usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	public Date getFechaCreacion() {
		return fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getUsuarioModificacion() {
		return usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public Date getFechaModificacion() {
		return fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getSexo() {
		return sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	public Set getRolusuarios() {
		return rolusuarios;
	}

	public void setRolusuarios(Set rolusuarios) {
		this.rolusuarios = rolusuarios;
	}

	public Set getUsuariodispositivos() {
		return usuariodispositivos;
	}

	public void setUsuariodispositivos(Set usuariodispositivos) {
		this.usuariodispositivos = usuariodispositivos;
	}

	public Set getUsuarioportafolios() {
		return usuarioportafolios;
	}

	public void setUsuarioportafolios(Set usuarioportafolios) {
		this.usuarioportafolios = usuarioportafolios;
	}

	public Set getRespuestacabeceras() {
		return respuestacabeceras;
	}

	public void setRespuestacabeceras(Set respuestacabeceras) {
		this.respuestacabeceras = respuestacabeceras;
	}

}
