package pe.com.cotic.test.modelo;

// Generated 14/09/2017 09:19:37 AM by Hibernate Tools 4.0.0

/**
 * Alternativa generated by hbm2java
 */
public class Alternativa implements java.io.Serializable {

	private Integer codigoAlternativa;
	private Pregunta pregunta;
	private String tituloAlternativa;
	private int flagRespuestaCorrectaAlternativa;
	private int estado;

	public Alternativa() {
	}

	public Alternativa(Pregunta pregunta, String tituloAlternativa,
			int flagRespuestaCorrectaAlternativa, int estado) {
		this.pregunta = pregunta;
		this.tituloAlternativa = tituloAlternativa;
		this.flagRespuestaCorrectaAlternativa = flagRespuestaCorrectaAlternativa;
		this.estado = estado;
	}

	public Integer getCodigoAlternativa() {
		return this.codigoAlternativa;
	}

	public void setCodigoAlternativa(Integer codigoAlternativa) {
		this.codigoAlternativa = codigoAlternativa;
	}

	public Pregunta getPregunta() {
		return this.pregunta;
	}

	public void setPregunta(Pregunta pregunta) {
		this.pregunta = pregunta;
	}

	public String getTituloAlternativa() {
		return this.tituloAlternativa;
	}

	public void setTituloAlternativa(String tituloAlternativa) {
		this.tituloAlternativa = tituloAlternativa;
	}

	public int getFlagRespuestaCorrectaAlternativa() {
		return this.flagRespuestaCorrectaAlternativa;
	}

	public void setFlagRespuestaCorrectaAlternativa(
			int flagRespuestaCorrectaAlternativa) {
		this.flagRespuestaCorrectaAlternativa = flagRespuestaCorrectaAlternativa;
	}

	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

}
