package pe.com.cotic.test.modelo;

// Generated 06/10/2017 10:40:55 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Menu generated by hbm2java
 */
public class Menu implements java.io.Serializable {

	private Integer codigoMenu;
	private int codigoMenuEnlace;
	private int nivelMenu;
	private int ordenMenu;
	private String nombreMenu;
	private String urlMenu;
	private String iconoMenu;
	private int estado;
	private Set rolmenus = new HashSet(0);

	public Menu() {
	}

	public Menu(int codigoMenuEnlace, int nivelMenu, int ordenMenu,
			String nombreMenu, int estado) {
		this.codigoMenuEnlace = codigoMenuEnlace;
		this.nivelMenu = nivelMenu;
		this.ordenMenu = ordenMenu;
		this.nombreMenu = nombreMenu;
		this.estado = estado;
	}

	public Menu(int codigoMenuEnlace, int nivelMenu, int ordenMenu,
			String nombreMenu, String urlMenu, String iconoMenu, int estado,
			Set rolmenus) {
		this.codigoMenuEnlace = codigoMenuEnlace;
		this.nivelMenu = nivelMenu;
		this.ordenMenu = ordenMenu;
		this.nombreMenu = nombreMenu;
		this.urlMenu = urlMenu;
		this.iconoMenu = iconoMenu;
		this.estado = estado;
		this.rolmenus = rolmenus;
	}

	public Integer getCodigoMenu() {
		return this.codigoMenu;
	}

	public void setCodigoMenu(Integer codigoMenu) {
		this.codigoMenu = codigoMenu;
	}

	public int getCodigoMenuEnlace() {
		return this.codigoMenuEnlace;
	}

	public void setCodigoMenuEnlace(int codigoMenuEnlace) {
		this.codigoMenuEnlace = codigoMenuEnlace;
	}

	public int getNivelMenu() {
		return this.nivelMenu;
	}

	public void setNivelMenu(int nivelMenu) {
		this.nivelMenu = nivelMenu;
	}

	public int getOrdenMenu() {
		return this.ordenMenu;
	}

	public void setOrdenMenu(int ordenMenu) {
		this.ordenMenu = ordenMenu;
	}

	public String getNombreMenu() {
		return this.nombreMenu;
	}

	public void setNombreMenu(String nombreMenu) {
		this.nombreMenu = nombreMenu;
	}

	public String getUrlMenu() {
		return this.urlMenu;
	}

	public void setUrlMenu(String urlMenu) {
		this.urlMenu = urlMenu;
	}

	public String getIconoMenu() {
		return this.iconoMenu;
	}

	public void setIconoMenu(String iconoMenu) {
		this.iconoMenu = iconoMenu;
	}

	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	public Set getRolmenus() {
		return this.rolmenus;
	}

	public void setRolmenus(Set rolmenus) {
		this.rolmenus = rolmenus;
	}

}
