package pe.com.cotic.test.modelo;

// Generated 07/09/2017 11:40:56 PM by Hibernate Tools 4.0.0

/**
 * Menu generated by hbm2java
 */
public class Menu implements java.io.Serializable {

	private int id;
	private Integer menuId;
	private Integer nivel;
	private Integer orden;
	private String nombre;
	private String url;
	private String icono;
	private Boolean estado;

	public Menu() {
	}

	public Menu(int id) {
		this.id = id;
	}

	public Menu(int id, Integer menuId, Integer nivel, Integer orden,
			String nombre, String url, String icono, Boolean estado) {
		this.id = id;
		this.menuId = menuId;
		this.nivel = nivel;
		this.orden = orden;
		this.nombre = nombre;
		this.url = url;
		this.icono = icono;
		this.estado = estado;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getMenuId() {
		return this.menuId;
	}

	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}

	public Integer getNivel() {
		return this.nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}

	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getIcono() {
		return this.icono;
	}

	public void setIcono(String icono) {
		this.icono = icono;
	}

	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

}
