package pe.com.cotic.test.modelo;

// Generated 17/11/2017 11:16:10 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Nivel generated by hbm2java
 */
public class Nivel implements java.io.Serializable {

	private Integer codigoNivel;
	private String descripcionNivel;
	private Set portafolios = new HashSet(0);
	private Set portafolios_1 = new HashSet(0);
	private Set usuarioportafolios = new HashSet(0);
	private Set portafolios_2 = new HashSet(0);

	public Nivel() {
	}

	public Nivel(String descripcionNivel) {
		this.descripcionNivel = descripcionNivel;
	}

	public Nivel(String descripcionNivel, Set portafolios, Set portafolios_1,
			Set usuarioportafolios, Set portafolios_2) {
		this.descripcionNivel = descripcionNivel;
		this.portafolios = portafolios;
		this.portafolios_1 = portafolios_1;
		this.usuarioportafolios = usuarioportafolios;
		this.portafolios_2 = portafolios_2;
	}

	public Integer getCodigoNivel() {
		return this.codigoNivel;
	}

	public void setCodigoNivel(Integer codigoNivel) {
		this.codigoNivel = codigoNivel;
	}

	public String getDescripcionNivel() {
		return this.descripcionNivel;
	}

	public void setDescripcionNivel(String descripcionNivel) {
		this.descripcionNivel = descripcionNivel;
	}

	public Set getPortafolios() {
		return this.portafolios;
	}

	public void setPortafolios(Set portafolios) {
		this.portafolios = portafolios;
	}

	public Set getPortafolios_1() {
		return this.portafolios_1;
	}

	public void setPortafolios_1(Set portafolios_1) {
		this.portafolios_1 = portafolios_1;
	}

	public Set getUsuarioportafolios() {
		return this.usuarioportafolios;
	}

	public void setUsuarioportafolios(Set usuarioportafolios) {
		this.usuarioportafolios = usuarioportafolios;
	}

	public Set getPortafolios_2() {
		return this.portafolios_2;
	}

	public void setPortafolios_2(Set portafolios_2) {
		this.portafolios_2 = portafolios_2;
	}

}
