package pe.com.cotic.test.modelo;

// Generated 14/09/2017 09:19:37 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Portafolio generated by hbm2java
 */
public class Portafolio implements java.io.Serializable {

	private Integer codigoPortafolio;
	private Nivel nivel;
	private String tituloPortafolio;
	private String descripcionPortafolio;
	private byte[] imagenPortafolio;
	private String fechaInicioPortafolio;
	private String fechaFinPortafolio;
	private int flagMostrarRespuestaCorrectaPortafolio;
	private int tiempoPortafolio;
	private int estado;
	private Set usuarioportafoliosForCodigoPortafolioEnlace = new HashSet(0);
	private Set usuarioportafoliosForCodigoPortafolio = new HashSet(0);
	private Set preguntas = new HashSet(0);

	public Portafolio() {
	}

	public Portafolio(Nivel nivel, String tituloPortafolio,
			String descripcionPortafolio, String fechaInicioPortafolio,
			int flagMostrarRespuestaCorrectaPortafolio, int tiempoPortafolio,
			int estado) {
		this.nivel = nivel;
		this.tituloPortafolio = tituloPortafolio;
		this.descripcionPortafolio = descripcionPortafolio;
		this.fechaInicioPortafolio = fechaInicioPortafolio;
		this.flagMostrarRespuestaCorrectaPortafolio = flagMostrarRespuestaCorrectaPortafolio;
		this.tiempoPortafolio = tiempoPortafolio;
		this.estado = estado;
	}

	public Portafolio(Nivel nivel, String tituloPortafolio,
			String descripcionPortafolio, byte[] imagenPortafolio,
			String fechaInicioPortafolio, String fechaFinPortafolio,
			int flagMostrarRespuestaCorrectaPortafolio, int tiempoPortafolio,
			int estado, Set usuarioportafoliosForCodigoPortafolioEnlace,
			Set usuarioportafoliosForCodigoPortafolio, Set preguntas) {
		this.nivel = nivel;
		this.tituloPortafolio = tituloPortafolio;
		this.descripcionPortafolio = descripcionPortafolio;
		this.imagenPortafolio = imagenPortafolio;
		this.fechaInicioPortafolio = fechaInicioPortafolio;
		this.fechaFinPortafolio = fechaFinPortafolio;
		this.flagMostrarRespuestaCorrectaPortafolio = flagMostrarRespuestaCorrectaPortafolio;
		this.tiempoPortafolio = tiempoPortafolio;
		this.estado = estado;
		this.usuarioportafoliosForCodigoPortafolioEnlace = usuarioportafoliosForCodigoPortafolioEnlace;
		this.usuarioportafoliosForCodigoPortafolio = usuarioportafoliosForCodigoPortafolio;
		this.preguntas = preguntas;
	}

	public Integer getCodigoPortafolio() {
		return this.codigoPortafolio;
	}

	public void setCodigoPortafolio(Integer codigoPortafolio) {
		this.codigoPortafolio = codigoPortafolio;
	}

	public Nivel getNivel() {
		return this.nivel;
	}

	public void setNivel(Nivel nivel) {
		this.nivel = nivel;
	}

	public String getTituloPortafolio() {
		return this.tituloPortafolio;
	}

	public void setTituloPortafolio(String tituloPortafolio) {
		this.tituloPortafolio = tituloPortafolio;
	}

	public String getDescripcionPortafolio() {
		return this.descripcionPortafolio;
	}

	public void setDescripcionPortafolio(String descripcionPortafolio) {
		this.descripcionPortafolio = descripcionPortafolio;
	}

	public byte[] getImagenPortafolio() {
		return this.imagenPortafolio;
	}

	public void setImagenPortafolio(byte[] imagenPortafolio) {
		this.imagenPortafolio = imagenPortafolio;
	}

	public String getFechaInicioPortafolio() {
		return this.fechaInicioPortafolio;
	}

	public void setFechaInicioPortafolio(String fechaInicioPortafolio) {
		this.fechaInicioPortafolio = fechaInicioPortafolio;
	}

	public String getFechaFinPortafolio() {
		return this.fechaFinPortafolio;
	}

	public void setFechaFinPortafolio(String fechaFinPortafolio) {
		this.fechaFinPortafolio = fechaFinPortafolio;
	}

	public int getFlagMostrarRespuestaCorrectaPortafolio() {
		return this.flagMostrarRespuestaCorrectaPortafolio;
	}

	public void setFlagMostrarRespuestaCorrectaPortafolio(
			int flagMostrarRespuestaCorrectaPortafolio) {
		this.flagMostrarRespuestaCorrectaPortafolio = flagMostrarRespuestaCorrectaPortafolio;
	}

	public int getTiempoPortafolio() {
		return this.tiempoPortafolio;
	}

	public void setTiempoPortafolio(int tiempoPortafolio) {
		this.tiempoPortafolio = tiempoPortafolio;
	}

	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	public Set getUsuarioportafoliosForCodigoPortafolioEnlace() {
		return this.usuarioportafoliosForCodigoPortafolioEnlace;
	}

	public void setUsuarioportafoliosForCodigoPortafolioEnlace(
			Set usuarioportafoliosForCodigoPortafolioEnlace) {
		this.usuarioportafoliosForCodigoPortafolioEnlace = usuarioportafoliosForCodigoPortafolioEnlace;
	}

	public Set getUsuarioportafoliosForCodigoPortafolio() {
		return this.usuarioportafoliosForCodigoPortafolio;
	}

	public void setUsuarioportafoliosForCodigoPortafolio(
			Set usuarioportafoliosForCodigoPortafolio) {
		this.usuarioportafoliosForCodigoPortafolio = usuarioportafoliosForCodigoPortafolio;
	}

	public Set getPreguntas() {
		return this.preguntas;
	}

	public void setPreguntas(Set preguntas) {
		this.preguntas = preguntas;
	}

}
