package pe.com.cotic.test.modelo;

// Generated 13/10/2017 03:11:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Pregunta generated by hbm2java
 */
public class Pregunta implements java.io.Serializable {

	private Integer codigoPregunta;
	private Portafolio portafolio;
	private String tituloPregunta;
	private int estado;
	private byte[] imagenPregunta;
	private Set alternativas = new HashSet(0);
	private Set alternativas_1 = new HashSet(0);
	private Set alternativas_2 = new HashSet(0);
	private Set respuestadetalles = new HashSet(0);

	public Pregunta() {
	}

	public Pregunta(Portafolio portafolio, String tituloPregunta, int estado) {
		this.portafolio = portafolio;
		this.tituloPregunta = tituloPregunta;
		this.estado = estado;
	}

	public Pregunta(Portafolio portafolio, String tituloPregunta, int estado,
			byte[] imagenPregunta, Set alternativas, Set alternativas_1,
			Set alternativas_2, Set respuestadetalles) {
		this.portafolio = portafolio;
		this.tituloPregunta = tituloPregunta;
		this.estado = estado;
		this.imagenPregunta = imagenPregunta;
		this.alternativas = alternativas;
		this.alternativas_1 = alternativas_1;
		this.alternativas_2 = alternativas_2;
		this.respuestadetalles = respuestadetalles;
	}

	public Integer getCodigoPregunta() {
		return this.codigoPregunta;
	}

	public void setCodigoPregunta(Integer codigoPregunta) {
		this.codigoPregunta = codigoPregunta;
	}

	public Portafolio getPortafolio() {
		return this.portafolio;
	}

	public void setPortafolio(Portafolio portafolio) {
		this.portafolio = portafolio;
	}

	public String getTituloPregunta() {
		return this.tituloPregunta;
	}

	public void setTituloPregunta(String tituloPregunta) {
		this.tituloPregunta = tituloPregunta;
	}

	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	public byte[] getImagenPregunta() {
		return this.imagenPregunta;
	}

	public void setImagenPregunta(byte[] imagenPregunta) {
		this.imagenPregunta = imagenPregunta;
	}

	public Set getAlternativas() {
		return this.alternativas;
	}

	public void setAlternativas(Set alternativas) {
		this.alternativas = alternativas;
	}

	public Set getAlternativas_1() {
		return this.alternativas_1;
	}

	public void setAlternativas_1(Set alternativas_1) {
		this.alternativas_1 = alternativas_1;
	}

	public Set getAlternativas_2() {
		return this.alternativas_2;
	}

	public void setAlternativas_2(Set alternativas_2) {
		this.alternativas_2 = alternativas_2;
	}

	public Set getRespuestadetalles() {
		return this.respuestadetalles;
	}

	public void setRespuestadetalles(Set respuestadetalles) {
		this.respuestadetalles = respuestadetalles;
	}

}
