package pe.com.cotic.test.modelo;

// Generated 07/09/2017 11:40:56 PM by Hibernate Tools 4.0.0

/**
 * Rolmenu generated by hbm2java
 */
public class Rolmenu implements java.io.Serializable {

	private int id;
	private Integer rolId;
	private Integer menuId;

	public Rolmenu() {
	}

	public Rolmenu(int id) {
		this.id = id;
	}

	public Rolmenu(int id, Integer rolId, Integer menuId) {
		this.id = id;
		this.rolId = rolId;
		this.menuId = menuId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getRolId() {
		return this.rolId;
	}

	public void setRolId(Integer rolId) {
		this.rolId = rolId;
	}

	public Integer getMenuId() {
		return this.menuId;
	}

	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}

}
