package pe.com.cotic.test.modelo;

// Generated 14/09/2017 09:19:37 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Usuariodispositivo generated by hbm2java
 */
public class Usuariodispositivo implements java.io.Serializable {

	private Integer codigoUsuarioDispositivo;
	private Usuario usuario;
	private String codigoDispositivo;
	private int estado;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;

	public Usuariodispositivo() {
	}

	public Usuariodispositivo(Usuario usuario, String codigoDispositivo,
			int estado, String usuarioCreacion, Date fechaCreacion) {
		this.usuario = usuario;
		this.codigoDispositivo = codigoDispositivo;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
	}

	public Usuariodispositivo(Usuario usuario, String codigoDispositivo,
			int estado, String usuarioCreacion, Date fechaCreacion,
			String usuarioModificacion, Date fechaModificacion) {
		this.usuario = usuario;
		this.codigoDispositivo = codigoDispositivo;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
	}

	public Integer getCodigoUsuarioDispositivo() {
		return this.codigoUsuarioDispositivo;
	}

	public void setCodigoUsuarioDispositivo(Integer codigoUsuarioDispositivo) {
		this.codigoUsuarioDispositivo = codigoUsuarioDispositivo;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getCodigoDispositivo() {
		return this.codigoDispositivo;
	}

	public void setCodigoDispositivo(String codigoDispositivo) {
		this.codigoDispositivo = codigoDispositivo;
	}

	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

}
