package pe.com.cotic.test.modelo;

// Generated 14/09/2017 09:19:37 AM by Hibernate Tools 4.0.0

/**
 * Version generated by hbm2java
 */
public class Version implements java.io.Serializable {

	private Integer codigoVersion;
	private String versionAplicacionVigente;
	private int versionUsuarios;
	private int versionPortafolio;
	private int versionNivel;

	public Version() {
	}

	public Version(String versionAplicacionVigente, int versionUsuarios,
			int versionPortafolio, int versionNivel) {
		this.versionAplicacionVigente = versionAplicacionVigente;
		this.versionUsuarios = versionUsuarios;
		this.versionPortafolio = versionPortafolio;
		this.versionNivel = versionNivel;
	}

	public Integer getCodigoVersion() {
		return this.codigoVersion;
	}

	public void setCodigoVersion(Integer codigoVersion) {
		this.codigoVersion = codigoVersion;
	}

	public String getVersionAplicacionVigente() {
		return this.versionAplicacionVigente;
	}

	public void setVersionAplicacionVigente(String versionAplicacionVigente) {
		this.versionAplicacionVigente = versionAplicacionVigente;
	}

	public int getVersionUsuarios() {
		return this.versionUsuarios;
	}

	public void setVersionUsuarios(int versionUsuarios) {
		this.versionUsuarios = versionUsuarios;
	}

	public int getVersionPortafolio() {
		return this.versionPortafolio;
	}

	public void setVersionPortafolio(int versionPortafolio) {
		this.versionPortafolio = versionPortafolio;
	}

	public int getVersionNivel() {
		return this.versionNivel;
	}

	public void setVersionNivel(int versionNivel) {
		this.versionNivel = versionNivel;
	}

}
