package pe.com.cotic.test.modelo;

// Generated 07/09/2017 11:40:56 PM by Hibernate Tools 4.0.0

/**
 * Version generated by hbm2java
 */
public class Version implements java.io.Serializable {

	private Integer codigoVersion;
	private String versionAplicacionVigente;
	private int versionUsuarios;
	private int versionCursos;

	public Version() {
	}

	public Version(String versionAplicacionVigente, int versionUsuarios,
			int versionCursos) {
		this.versionAplicacionVigente = versionAplicacionVigente;
		this.versionUsuarios = versionUsuarios;
		this.versionCursos = versionCursos;
	}

	public Integer getCodigoVersion() {
		return this.codigoVersion;
	}

	public void setCodigoVersion(Integer codigoVersion) {
		this.codigoVersion = codigoVersion;
	}

	public String getVersionAplicacionVigente() {
		return this.versionAplicacionVigente;
	}

	public void setVersionAplicacionVigente(String versionAplicacionVigente) {
		this.versionAplicacionVigente = versionAplicacionVigente;
	}

	public int getVersionUsuarios() {
		return this.versionUsuarios;
	}

	public void setVersionUsuarios(int versionUsuarios) {
		this.versionUsuarios = versionUsuarios;
	}

	public int getVersionCursos() {
		return this.versionCursos;
	}

	public void setVersionCursos(int versionCursos) {
		this.versionCursos = versionCursos;
	}

}
